databases:
  - name: Hello_rails
    databaseName: Hello_rails
    user: postgres
    password: azazel

services:
  - type: web
    name: Hello_rails
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Hello_rails
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false